name: savethefood
description: "A new Flutter project."
publish_to: "none"
version: 1.0.0+1

environment:
  sdk: ">=2.18.0 <3.0.0"

dependencies:
  flutter:
    sdk: flutter
  geolocator: ^9.0.1
  firebase_core: ^3.2.0
  firebase_database: ^11.0.3
  cloud_firestore: ^5.1.0
  firebase_auth: ^5.1.2
  provider: ^6.1.2
  cupertino_icons: ^1.0.2
  share_plus: ^7.2.2
  google_nav_bar: ^5.0.6
  permission_handler: ^11.3.1
  firebase_messaging: ^15.0.3
  flutter_local_notifications: ^17.2.1+2
  http: ^1.2.2
  intl: ^0.19.0
  shared_preferences: ^2.2.3
  url_launcher: ^6.3.0
  image_picker: ^1.1.2
  firebase_storage: ^12.1.1

dev_dependencies:
  flutter_test:
    sdk: flutter
  flutter_lints: ^3.0.1

flutter:
  uses-material-design: true

  assets:
    - lib/img/
    - lib/imag/
