// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.windows:
        return windows;
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyDGXCyfnGg0kb8Mtv0EikmUBlAmXYakjf4',
    appId: '1:315438283802:web:27dd22f8354a86cd88a5a3',
    messagingSenderId: '315438283802',
    projectId: 'savethefood-b287a',
    authDomain: 'savethefood-b287a.firebaseapp.com',
    storageBucket: 'savethefood-b287a.appspot.com',
    measurementId: 'G-21JQ8HML7C',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyAxYUrlVtLvUgEgHleN29jm69kcKTOGHwk',
    appId: '1:315438283802:android:76117e333f80f71a88a5a3',
    messagingSenderId: '315438283802',
    projectId: 'savethefood-b287a',
    storageBucket: 'savethefood-b287a.appspot.com',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyAehN4__yjGq3MUjXhxdU2HbgCf2kgAKeE',
    appId: '1:315438283802:ios:41b53816b8f7374588a5a3',
    messagingSenderId: '315438283802',
    projectId: 'savethefood-b287a',
    storageBucket: 'savethefood-b287a.appspot.com',
    iosBundleId: 'com.example.ecommerceApp',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyAehN4__yjGq3MUjXhxdU2HbgCf2kgAKeE',
    appId: '1:315438283802:ios:41b53816b8f7374588a5a3',
    messagingSenderId: '315438283802',
    projectId: 'savethefood-b287a',
    storageBucket: 'savethefood-b287a.appspot.com',
    iosBundleId: 'com.example.ecommerceApp',
  );

  static const FirebaseOptions windows = FirebaseOptions(
    apiKey: 'AIzaSyDGXCyfnGg0kb8Mtv0EikmUBlAmXYakjf4',
    appId: '1:315438283802:web:a3213a103b3335ba88a5a3',
    messagingSenderId: '315438283802',
    projectId: 'savethefood-b287a',
    authDomain: 'savethefood-b287a.firebaseapp.com',
    storageBucket: 'savethefood-b287a.appspot.com',
    measurementId: 'G-ZTQD6WPZNQ',
  );

}